
[Interface]
PrivateKey = CCXsAftXqqQZykKLHl5654c5hdPI9F5wJ3S+iE0ZE10=
Address = 10.8.0.7/24
DNS = 1.1.1.1


[Peer]
PublicKey = 2ZreRoc3cOf4k240/J3dpf8vy3j86dW72xJYH7c3Fi4=
PresharedKey = MIJttrXzI39Xpm4ZarRLBSm8YT+BayHjTXiSOucFk1Q=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 195.133.9.238:51820