
[Interface]
PrivateKey = OIZfb3a9g5X6ztP0a+KZv+b3P/M/bcU4TMS51U0S9Vw=
Address = 10.8.0.18/24
DNS = 1.1.1.1


[Peer]
PublicKey = 44TqELc4VYgj06bfysHo8oVbglgILfBUdo5+S19hdDk=
PresharedKey = n7Y8+tE6Xy0rqz3a9EaXFAnndEFaLBaybIOXhfdGMmc=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 185.230.190.165:51820